CC := gcc-7
CFLAGS := -std=c99 -g3 -Og -fstack-protector --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fPIC -pie -w

default: all

bit_print: bit_print.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

calc: calc.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

calc_adv: calc_adv.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $< -lm

cbd_lawn: cbd_lawn.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

cbd_pennies: cbd_pennies.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

cbd_pennies_adv: cbd_pennies_adv.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

cbd_rand: cbd_rand.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

cbd_rand_dist: cbd_rand_dist.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

cbd_time: cbd_time.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

cbd_triple_int: cbd_triple_int.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

char_arrays: char_arrays.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

convert: convert.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

countchar: countchar.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

digit_count: digit_count.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

double: double.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-10: ex_1-10.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-12: ex_1-12.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-13: ex_1-13.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-14: ex_1-14.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-14a: ex_1-14a.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-15: ex_1-15.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-16: ex_1-16.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-17: ex_1-17.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-19: ex_1-19.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-23: ex_1-23.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-3: ex_1-3.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-4: ex_1-4.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-5: ex_1-5.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-7: ex_1-7.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-8: ex_1-8.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_1-9: ex_1-9.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_2-4: ex_2-4.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_2-5: ex_2-5.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_3-3: ex_3-3.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_3-5: ex_3-5.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_3-6: ex_3-6.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_4-1: ex_4-1.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_4-12: ex_4-12.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_4-13: ex_4-13.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_4-2: ex_4-2.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_5-1: ex_5-1.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_5-10: ex_5-10.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_5-13: ex_5-13.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_5-14: ex_5-14.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_5-3: ex_5-3.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_5-4: ex_5-4.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_5-5: ex_5-5.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_5-7: ex_5-7.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ex_5-8: ex_5-8.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

for: for.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

get_chars: get_chars.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

hello: hello.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

limits_of_c_lang: limits_of_c_lang.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

line_counter: line_counter.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

primes: primes.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

ranges: ranges.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

shell_sort: shell_sort.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

srs_lib: srs_lib.c struct.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $?

stack_address: stack_address.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

struct: struct.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

temp_conv: temp_conv.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

temp_conv2: temp_conv2.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

test_get_char: test_get_char.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

variable_arrays: variable_arrays.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

word_count: word_count.c
	@echo CC $@
	@$(CC) $(CFLAGS) -o $@ $<

all: bit_print calc calc_adv cbd_lawn cbd_pennies cbd_pennies_adv cbd_rand cbd_rand_dist cbd_time cbd_triple_int char_arrays convert countchar digit_count double ex_1-10 ex_1-12 ex_1-13 ex_1-14 ex_1-14a ex_1-15 ex_1-16 ex_1-17 ex_1-19 ex_1-23 ex_1-3 ex_1-4 ex_1-5 ex_1-7 ex_1-8 ex_1-9 ex_2-4 ex_2-5 ex_3-3 ex_3-5 ex_3-6 ex_4-1 ex_4-12 ex_4-13 ex_4-2 ex_5-1 ex_5-10 ex_5-13 ex_5-14 ex_5-3 ex_5-4 ex_5-5 ex_5-7 ex_5-8 for get_chars hello limits_of_c_lang line_counter primes ranges shell_sort srs_lib stack_address struct temp_conv temp_conv2 test_get_char variable_arrays word_count 

clean:
	@echo Removing compiled files
	@rm -f bit_print calc calc_adv cbd_lawn cbd_pennies cbd_pennies_adv cbd_rand cbd_rand_dist cbd_time cbd_triple_int char_arrays convert countchar digit_count double ex_1-10 ex_1-12 ex_1-13 ex_1-14 ex_1-14a ex_1-15 ex_1-16 ex_1-17 ex_1-19 ex_1-23 ex_1-3 ex_1-4 ex_1-5 ex_1-7 ex_1-8 ex_1-9 ex_2-4 ex_2-5 ex_3-3 ex_3-5 ex_3-6 ex_4-1 ex_4-12 ex_4-13 ex_4-2 ex_5-1 ex_5-10 ex_5-13 ex_5-14 ex_5-3 ex_5-4 ex_5-5 ex_5-7 ex_5-8 for get_chars hello limits_of_c_lang line_counter primes ranges shell_sort srs_lib stack_address struct temp_conv temp_conv2 test_get_char variable_arrays word_count 

